# -*- coding: utf-8 -*-
"""Question2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xGZ6pllPaoPQjuw6-Fo7GfHPx352xr6I
"""

!gdown 1jfSKBXJwvH7tfDRvTYO-CMc91XFhQch1

from google.colab import drive
drive.mount('/content/drive')

!unzip Project1_data.zip

import pandas as pd

R1400P2 = pd.read_excel("R1400.xlsx", sheet_name='R1400P2')
R1401P2 = pd.read_excel("R1401.xlsx", sheet_name='R1401P2')
R98P2 = pd.read_excel("R98.xlsx", sheet_name='R98P2')
R99P2 = pd.read_excel("R99.xlsx", sheet_name='R99P2')
U1400P2 = pd.read_excel("U1400.xlsx", sheet_name='U1400P2')
U98P2 = pd.read_excel("U98.xlsx", sheet_name='U98P2')
U99P2 = pd.read_excel("U99.xlsx", sheet_name='U99P2')

R1400P2_Vech = R1400P2[["vehicle", "motorcycle", "bicycle"]].copy()
R1400P2_Vech.replace({True: 1, False: 0}, inplace=True)

R1401P2_Vech = R1401P2[["vehicle", "motorcycle", "bicycle"]].copy()
R1401P2_Vech.replace({True: 1, False: 0}, inplace=True)

R98P2_Vech = R98P2[["vehicle", "motorcycle", "bicycle"]].copy()
R98P2_Vech.replace({True: 1, False: 0}, inplace=True)

R99P2_Vech = R99P2[["vehicle", "motorcycle", "bicycle"]].copy()
R99P2_Vech.replace({True: 1, False: 0}, inplace=True)

U1400P2_Vech = U1400P2[["vehicle", "motorcycle", "bicycle"]].copy()
U1400P2_Vech.replace({True: 1, False: 0}, inplace=True)

U98P2_Vech = U98P2[["vehicle", "motorcycle", "bicycle"]].copy()
U98P2_Vech.replace({True: 1, False: 0}, inplace=True)

U99P2_Vech = U99P2[["vehicle", "motorcycle", "bicycle"]].copy()
U99P2_Vech.replace({True: 1, False: 0}, inplace=True)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
import matplotlib.pyplot as plt

R1400P2_Vech['Year'] = 'R1400'
R1401P2_Vech['Year'] = 'R1401'
R98P2_Vech['Year'] = 'R98'
R99P2_Vech['Year'] = 'R99'
U1400P2_Vech['Year'] = 'U1400'
U98P2_Vech['Year'] = 'U98'
U99P2_Vech['Year'] = 'U99'

all_data = pd.concat([R1400P2_Vech, R1401P2_Vech, R98P2_Vech, R99P2_Vech, U1400P2_Vech, U98P2_Vech, U99P2_Vech])

vehicle_distribution = all_data.groupby('Year').sum()

plt.figure(figsize=(14, 7))
width = 0.25

x = range(len(vehicle_distribution))

plt.bar([pos - width for pos in x], vehicle_distribution['vehicle'], width=width, label='Car')
plt.bar(x, vehicle_distribution['motorcycle'], width=width, label='Motorcycle')
plt.bar([pos + width for pos in x], vehicle_distribution['bicycle'], width=width, label='Bicycle')

plt.title('Distribution of Household Vehicle Usage by Year')
plt.xlabel('Year')
plt.ylabel('Number of Vehicles')
plt.xticks(ticks=x, labels=vehicle_distribution.index)
plt.legend(title='Vehicle Types', loc='upper center', bbox_to_anchor=(0.5, -0.15), ncol=3, frameon=False)

plt.tight_layout()
plt.show()

